import React from "react";

export const PremiumFooter: React.FC = () => {
    return (
        <footer className="max-w-7xl mx-auto mt-32 pb-16 relative z-10 border-t border-white/5 pt-16">
            <div className="grid md:grid-cols-4 gap-12">
                <div className="space-y-6 col-span-2">
                    <div className="flex items-center gap-3">
                        <div className="w-8 h-8 bg-gradient-to-tr from-accent-blue to-accent-purple rounded-lg" />
                        <h3 className="text-xl font-bold font-header">AutoStream</h3>
                    </div>
                    <p className="text-gray-500 text-sm max-w-sm leading-relaxed">
                        Leading the autonomous orchestration of marketing visualisations for the Australian enterprise.
                        8K assets generated by Picasso & DiCaprio.
                    </p>
                </div>

                <div className="space-y-4">
                    <h4 className="text-white font-bold text-sm uppercase tracking-widest font-header">Agents</h4>
                    <ul className="text-gray-500 text-sm space-y-2">
                        <li>The Director</li>
                        <li>Picasso (Visuals)</li>
                        <li>DiCaprio (Motion)</li>
                        <li>Scraper Orchestrator</li>
                    </ul>
                </div>

                <div className="space-y-4">
                    <h4 className="text-white font-bold text-sm uppercase tracking-widest font-header">Platform</h4>
                    <ul className="text-gray-500 text-sm space-y-2 cursor-pointer">
                        <li className="hover:text-accent-blue transition-colors">Campaigns</li>
                        <li className="hover:text-accent-blue transition-colors">Asset Library</li>
                        <li className="hover:text-accent-blue transition-colors">Locale Settings</li>
                        <li className="hover:text-accent-blue transition-colors">API Keys</li>
                    </ul>
                </div>
            </div>

            <div className="mt-16 flex flex-col md:flex-row justify-between items-center gap-6 text-[10px] text-gray-600 font-mono tracking-[0.2em] uppercase">
                <div>© 2026 AutoStream Labs // G-Pilot Engine // Gemini 3 Pro Core</div>
                <div className="flex gap-8">
                    <span>Privacy Protocol</span>
                    <span>Terms of Sovereignty</span>
                    <span className="text-accent-blue font-bold">Powered by Nano Banana V3.1</span>
                </div>
            </div>
        </footer>
    );
};
